language: node_js
node_js:
  - "0.12"

# before_install:
#   - "npm i -g gulp mocha istanbul codeclimate-test-reporter"
#   - "npm i --save coveralls mocha-lcov-reporter"

# addons:
#   code_climate:
#     repo_token: -
#   coveralls:
#     repo_token: -

# before_script:
#   - "gulp webserver &"

# after_script:
#   - "cat ./coverage/lcov.info | codeclimate"
#   - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"